/**
 * @module imagen
 * AI image generation using Gemini's native image capabilities.
 * Generates branded visuals, thumbnails, slides, and promotional images.
 *
 * Usage:
 *   import { createImageGenerator } from '@krusch/toolkit/imagen';
 *   const imagen = createImageGenerator({ apiKey: '...', outputDir: './images' });
 *   const result = await imagen.generate('A professional thumbnail', { aspect: '9:16' });
 */

import { GoogleGenAI } from '@google/genai';
import { mkdirSync, writeFileSync, existsSync } from 'fs';

/** @type {GoogleGenAI|null} */
let _client = null;

/**
 * @typedef {object} ImageConfig
 * @property {string} apiKey - Gemini API key
 * @property {string} [model='imagen-4.0-generate-001'] - Imagen model for image generation
 * @property {string} outputDir - Directory to save generated images
 */

/**
 * Create an image generator instance.
 *
 * @param {ImageConfig} config
 * @returns {object} Image generator with generate(), thumbnail(), slide(), promo() methods
 */
export function createImageGenerator(config) {
    const { apiKey, model = 'imagen-4.0-generate-001', outputDir } = config;

    function getClient() {
        if (!_client) {
            _client = new GoogleGenAI({ apiKey });
        }
        return _client;
    }

    function ensureOutputDir() {
        if (!existsSync(outputDir)) {
            mkdirSync(outputDir, { recursive: true });
        }
    }

    /**
     * Generate an image from a text prompt.
     *
     * @param {string} prompt - Image generation prompt
     * @param {object} [options]
     * @param {string} [options.prefix='img'] - Filename prefix
     * @param {number} [options.numberOfImages=1] - Number of images to generate
     * @returns {Promise<{filename: string, filepath: string}>}
     */
    async function generate(prompt, options = {}) {
        ensureOutputDir();
        const client = getClient();
        const { prefix = 'img', numberOfImages = 1 } = options;

        try {
            const response = await client.models.generateImages({
                model,
                prompt,
                config: { numberOfImages },
            });

            if (!response.generatedImages || response.generatedImages.length === 0) {
                throw new Error('No images generated by Imagen API');
            }

            const imgBytes = response.generatedImages[0].image.imageBytes;
            const buffer = Buffer.from(imgBytes, 'base64');
            const filename = `${prefix}_${Date.now()}.png`;
            const filepath = `${outputDir}/${filename}`;
            writeFileSync(filepath, buffer);
            return { filename, filepath };
        } catch (err) {
            console.error(`❌ Image generation failed: ${err.message}`);
            throw err;
        }
    }

    /**
     * Generate a branded thumbnail with space for text overlay.
     *
     * @param {string} topic - Topic title
     * @param {object} [options]
     * @param {string} [options.aspect='9:16'] - Aspect ratio
     * @param {string} [options.brandContext] - Brand styling instructions
     * @returns {Promise<{filename: string, filepath: string}>}
     */
    async function thumbnail(topic, options = {}) {
        const { aspect = '9:16', brandContext = '' } = options;
        const prompt = `Create a professional, eye-catching social media thumbnail.
TOPIC: ${topic}
STYLE: ${aspect === '9:16' ? 'Vertical 9:16' : 'Landscape 16:9'} format.
${brandContext}
Bold, large text overlay area (leave space for text to be added later).
Dramatic lighting, modern design, gradient background. Clean, not cluttered — premium feel.
NO actual text in the image — just the visual background/scene.`;

        return generate(prompt, { prefix: 'thumb' });
    }

    /**
     * Generate a slide image for a slideshow.
     *
     * @param {string} slideText - Text content for the slide
     * @param {number} slideNumber - Slide position number
     * @param {object} [options]
     * @param {string} [options.brandContext] - Brand styling instructions
     * @returns {Promise<{filename: string, filepath: string}>}
     */
    async function slide(slideText, slideNumber, options = {}) {
        const { brandContext = '' } = options;
        const prompt = `Create a single, clean social media slide image.
SLIDE ${slideNumber}: "${slideText}"
STYLE: Vertical 9:16 format. ${brandContext}
The slide text should be prominently displayed in large, bold white text.
Background should be a subtle gradient or abstract visual. Professional and modern.`;

        return generate(prompt, { prefix: `slide_${slideNumber}` });
    }

    /**
     * Generate a promotional image.
     *
     * @param {string} topic - Topic title
     * @param {'cinematic'|'clean'|'editorial'|'infographic'} [style='cinematic'] - Visual style
     * @param {object} [options]
     * @param {string} [options.brandContext] - Brand styling instructions
     * @returns {Promise<{filename: string, filepath: string}>}
     */
    async function promo(topic, style = 'cinematic', options = {}) {
        const { brandContext = '' } = options;
        const styles = {
            cinematic: 'Dramatic cinematic lighting, movie poster feel, dark moody tones',
            clean: 'Clean minimalist design, lots of whitespace, subtle gradients',
            editorial: 'Magazine editorial style, bold typography placement area, sharp contrast',
            infographic: 'Data visualization aesthetic, charts and numbers feel, modern and structured',
        };

        const prompt = `Create a professional marketing image for social media.
TOPIC: ${topic}
STYLE: ${styles[style] || styles.cinematic}
${brandContext}
No text — just the visual that conveys authority, trust, and quality.`;

        return generate(prompt, { prefix: `promo_${style}` });
    }

    return { generate, thumbnail, slide, promo };
}
