import { createPersona } from '../factory.js';

export const schema = {
    name: "build_persona",
    description: "Build and register a synthetic persona on a specific node based on a JSON blueprint.",
    parameters: {
        type: "object",
        properties: {
            node: { type: "string", enum: ["kruschgame", "kruschdev"], description: "Target node for the persona" },
            blueprint: { type: "object", description: "The JSON blueprint generated by synthesize_persona" }
        },
        required: ["node", "blueprint"]
    }
};

export async function execute(args) {
    try {
        await createPersona(args.node, args.blueprint);
        return { success: true, message: `Persona ${args.blueprint.name} built successfully on ${args.node}.` };
    } catch (e) {
        return { error: `Build failed: ${e.message}` };
    }
}
