import { exec } from 'node:child_process';
import util from 'node:util';
import fs from 'node:fs/promises';
import { generateModelfile } from './modelfile.js';

const execAsync = util.promisify(exec);

import { chatJson } from '../llm.js';
import { query, embedText } from './db-pg.js';
import { envOr } from '../config.js';

/**
 * Dynamically synthesizes a new persona blueprint via LLM if a requested skill does not exist.
 *
 * @param {string} personaName - The desired name of the new persona.
 * @param {string} domain - The project or domain context for the persona.
 * @returns {Promise<Object>} JSON blueprint for the persona.
 */
export async function synthesizePersonaBlueprint(personaName, domain) {
    const system = `You are the Factory Agent for the Krusch homelab.
The Orchestrator requested a new specialized persona named '${personaName}' for the domain '${domain}'.
This persona does not exist. Your task is to generate the JSON specification for this new persona.
Rules:
1. The base model must be 'qwen2.5-coder:7b' or similar for local execution, or 'gemini-2.5-flash-lite' if it requires cloud/heavy data parsing.
2. The persona MUST be extremely targeted and single-purpose ("one-shot"). The 'skill' description must be less than 2 sentences and describe exactly ONE task this persona will execute (e.g., "You only validate CSS"). Do not include general agent fluff.
3. The host 'node' must be 'kruschgame' or 'kruschdev'.

Output strictly valid JSON matching this schema:
{
  "name": "persona-name",
  "base": "model-name",
  "node": "kruschgame",
  "skill": "You are a ...",
  "project": "${domain}",
  "toolsets": ["FileSystem", "Core"]
}

For the "toolsets" array, choose ONLY from these available ADK 2.0 SkillToolsets:
- FileSystem: Read/write files
- Execution: Run shell commands (for sys/infra personas)
- Analysis: Static code analysis
- Sandbox: Containerized execution
- Core: Standard communication (RAG search, shared memory).

EXTREME DISTILLATION: Pick ONLY the absolute minimum toolsets needed for the ONE task. If it only reads, just give it FileSystem. Fewer is better.`;
    
    // Wire the Factory Persona to Gemini Flash-Lite to guarantee perfect schema output (Sec 8.1)
    const apiKey = envOr('GEMINI_API_KEY', null, process.env.GEMINI_API_KEY);
    let useGemini = !!apiKey;
    const config = useGemini ? {
        provider: 'gemini',
        model: envOr('GEMINI_FAST_MODEL', null, 'gemini-2.5-flash-lite'),
        apiKey: apiKey,
        maxTokens: 1000,
        temperature: 0.2
    } : {
        provider: 'ollama',
        apiUrl: envOr('CHRYSALIS_DIRECTOR_URL', null, 'http://localhost:11434/v1/chat/completions'),
        model: envOr('CHRYSALIS_DIRECTOR_MODEL', null, 'qwen2.5-coder:14b'), // Large reasoning model fallback
        maxTokens: 1000,
        temperature: 0.2,
        format: 'json'
    };

    console.log(`[Factory] Synthesizing blueprint for '${personaName}' via ${config.provider} (${config.model})...`);
    try {
        const spec = await chatJson(system, `Generate the blueprint for '${personaName}'`, config);
        spec.name = personaName; // Ensure no drift
        spec.project = domain;
        return spec;
    } catch (e) {
        throw new Error(`[Factory Error] Blueprint synthesis failed: ${e.message}`);
    }
}

/**
 * Creates and persists a synthetic persona, including building its Ollama Modelfile
 * and saving it to the PostgreSQL registry with embeddings.
 *
 * @param {string} targetHost - The target node to host the persona ('kruschdev' or 'kruschgame').
 * @param {Object} personaSpec - The JSON blueprint generated by synthesizePersonaBlueprint.
 * @returns {Promise<void>}
 */
export async function createPersona(targetHost, personaSpec) {
  if (!personaSpec || !personaSpec.name || !/^[A-Za-z0-9_-]+$/.test(personaSpec.name) || personaSpec.name === 'undefined') {
      throw new Error(`[Factory Error] Invalid persona name: ${personaSpec?.name}`);
  }
  if (personaSpec.skill && personaSpec.skill.length > 800) {
      throw new Error(`[Factory Error] Persona skill size exceeds maximum limit. We want small persona + 1 skill. Length: ${personaSpec.skill.length} (Max 800)`);
  }

  const modelfileContent = generateModelfile(personaSpec);
  const modelfilePath = `/tmp/Modelfile_${personaSpec.name}`;
  
  await fs.writeFile(modelfilePath, modelfileContent);
  
  console.log(`[Factory] Building persona ${personaSpec.name} on ${targetHost}...`);
  try {
    if (targetHost.startsWith('kruschdev')) {
       // Route to the appropriate container based on persona type
       const name = personaSpec.name.toLowerCase();
       const containerName = (name.includes('manager') || name.includes('director') || name.includes('officer'))
           ? 'edge-director'
           : 'edge-worker';

       await execAsync(`docker cp "${modelfilePath}" ${containerName}:"${modelfilePath}"`);
       await execAsync(`docker exec ${containerName} ollama create "${personaSpec.name}" -f "${modelfilePath}"`);
       await execAsync(`docker exec ${containerName} rm -f "${modelfilePath}"`);
    } else if (targetHost === 'kruschgame') {
       // Warm Base Pattern: Specialists on kruschgame don't need 'ollama create'.
       // They use 'qwen2.5-coder:7b' + a dynamic System Prompt at runtime.
       console.log(`[Factory] Specialist persona '${personaSpec.name}' bypasses model creation; handles via Warm Base.`);
    } else {
       throw new Error(`Unknown host ${targetHost}`);
    }
    
    console.log(`[Factory] Generating embedding for synthetic persona ${personaSpec.name}...`);
    let embeddingVector = null;
    try {
        const descriptionToEmbed = `Persona: ${personaSpec.name}\nProject: ${personaSpec.project}\nSkill: ${personaSpec.skill}`;
        embeddingVector = await embedText(descriptionToEmbed);
    } catch (embErr) {
        console.warn(`[Factory] Failed to generate embedding: ${embErr.message}`);
    }

    // Save generated blueprint to Postgres for tracking and vector search
    await query(`
        INSERT INTO personas (name, base_model, node, skill, project_domain, is_synthetic, embedding, tools)
        VALUES ($1, $2, $3, $4, $5, true, $6, $7)
        ON CONFLICT (name) DO UPDATE SET
            base_model = EXCLUDED.base_model,
            node = EXCLUDED.node,
            skill = EXCLUDED.skill,
            project_domain = EXCLUDED.project_domain,
            is_synthetic = true,
            embedding = COALESCE(EXCLUDED.embedding, personas.embedding),
            tools = EXCLUDED.tools
    `, [personaSpec.name, personaSpec.base || 'qwen2.5-coder:7b', targetHost, personaSpec.skill, personaSpec.project || 'unknown', embeddingVector, personaSpec.toolsets || personaSpec.tools || []]);
    
    console.log(`[Factory] Saved ${personaSpec.name} to Postgres successfully.`);
  } finally {
     await fs.unlink(modelfilePath).catch(() => {});
  }
}
